#!/bin/sh

# Get kubeconfig from SSM Parameter Store
aws ssm get-parameters \
    --names KUBECONFIG \
    --with-decryption \
    --query "Parameters[].Value" \
    --output text \
    > $KUBECONFIG

# Lookup Instance ID
INSTANCE_ID=$(aws ssm describe-instance-information \
    --filter "Key=tag:project,Values=kube-lambda-ssm-spike" \
    --query "InstanceInformationList[].InstanceId[]" \
    --output text)

echo "Instance ID is: $INSTANCE_ID, starting port forward session"

# Start port forward
aws ssm start-session \
    --target $INSTANCE_ID \
    --document-name AWS-StartPortForwardingSession \
    --parameters '{"portNumber":["6443"],"localPortNumber":["6443"]}' &

# Run kubectl commands
kubectl get svc,deployment --all-namespaces
